[theme]
primaryColor = "#73bd5d"
backgroundColor = "#f8faf7"
secondaryBackgroundColor = "#ffffff"
textColor = "#1a1a1a"
font = "sans serif"

[server]
headless = true
runOnSave = true
port = 8501
maxUploadSize = 25

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"